### ISSUE TITLE
New illustrations for the Data Hazards 🎨

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-hazards#118]
The current Data Hazard labels were created at the beginning of this project, but now we are lucky to be working with the wonderful @vairylein and Yasmin to redesign them. 

This will mean that they will look more consistent in the cool tools that have been made to present the labels - at the moment several of the Hazards have thinner outlines than others which makes them look a little odd.

**Comment by PogromcaPapai** [comment]
While we're at it, I think it might be a good idea to create mini versions of the labels. As you can see here, the text is not really visible in the badge. It's also hard to see that the hammer is hitting a screw and not a nail. Similarly, "lacks community involvement" and "ignores or opposes community needs" is only distinguishable using the length of the text.
![Example labels](https://notch-marble-primrose.glitch.me/labels?d=misuse,lacks,ignores)
I love all the other symbols though!!

**Comment by ninadicara** [comment]
> While we're at it, I think it might be a good idea to create mini versions of the labels. As you can see here, the text is not really visible in the badge. It's also hard to see that the hammer is hitting a screw and not a nail. Similarly, "lacks community involvement" and "ignores or opposes community needs" is only distinguishable using the length of the text. ![Example labels](https://camo.githubusercontent.com/c45c04d3b926a182de1be72e491590d62c30ca1c1353d7b004fd5f4c06ab5db1/68747470733a2f2f6e6f7463682d6d6172626c652d7072696d726f73652e676c697463682e6d652f6c6162656c733f643d6d69737573652c6c61636b732c69676e6f726573) I love all the other symbols though!!

Yes this is a really good point! Will mention this the next time we see the illustrator :)

**Comment by ninadicara** [comment]
The labels themselves are now complete - yay! We're continuing to work with Vanessa and Yasmin on some animations (!) and GIF versions of the Hazards too. 

For now, we need the updated Hazards on the website.
