### ISSUE TITLE
Showcase preparation

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-hazards#125]
- [x] Check ethics timeline is still valid 
- [x] Update Eventbrite with time
- [ ] Possibly add question(s) to survey for project owners asking if they use ay other ethics frameworks/panels/etc (or plan to) and what this added? 
- [ ] Invite project owners to Showcase (1 or 2?)
- [ ] Print physical forms
- [ ] Update the slides and check we have links for everything etc (advertise data week)

**Comment by ninadicara** [comment]
Showcase complete!
