### ISSUE TITLE
Facilitator training workshops

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-hazards#126]
Facilitator training being organised [on this folder in Sharepoint](https://uob.sharepoint.com/:f:/r/teams/grp-ethicaldatascience/Shared%20Documents/Data%20Hazards/Facilitator%20Training%202022?csf=1&web=1&e=5aQb0S) - just for ease of use.

**Comment by NatalieZelenka** [comment]
- [ ] Add Ismael as a contributor for this

**Comment by ninadicara** [comment]
Added IKG to contributors in PR #169
