### ISSUE TITLE
Website Updates

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-hazards#130]
- [x] Timeline
- [x] Dark mode - turn off ?
- [x] Fix title
- [ ] Header colours - green?
- [ ] New Hazard labels 
- [ ] Move contributors list to the front page and sub-page of About 
- [ ] link to join the slack(/QR code?)
- [ ] downloadable .ics for co-working meetings
- [ ] new hazard label image on README
- [x] Add redirect for datahazards.com/labels

**Comment by NatalieZelenka** [comment]
Dark mode fix: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#configure-default-mode
