### ISSUE TITLE
Website dark mode difficult to read

### ISSUE THREAD

**Issue by Lextuga007** [very-good-science/data-hazards#134]
The page https://datahazards.com/contents/data-hazards.html doesn't come through in an accessible format in dark mode unfortunately. I get a dark background and then white text on the yellow boxes. I was using Edge if that is also helpful to know.

**Comment by NatalieZelenka** [comment]
Thanks Zoe! You can turn off dark mode, but this is a bug which I am
trying to solve! Thanks for letting us know!

**Comment by Lextuga007** [comment]
I thought it was my own settings! I hadn't realised it was on the page itself. Thanks for the update 🙂

**Comment by Lextuga007** [comment]
Nice, it's ok now (but I had to clear cookies in Edge to refresh it). Thanks

**Comment by Lextuga007** [comment]
Yes thanks for checking 😄
