### ISSUE TITLE
Add Mozilla Privacy not included to privacy safety precautions

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-hazards#139]
- The methodology page: https://foundation.mozilla.org/en/privacynotincluded/about/methodology/ may be useful

**Comment by ninadicara** [comment]
I've added this to a new page of tools related to the Data Hazards (I didn't think it made sense as a safety precaution if we're thinking they should be quite general, and it seemed more like a complementary method). This is in PR #169
