### ISSUE TITLE
Alt text

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-hazards#14]
Need to add alt text to hazard labels.

Update 7.03.2022:
There are now alt text labels on all of the individual hazard page labels, but not on the main overview page.

**Comment by NatalieThurlby** [comment]
I couldn't see how to do this in the sphinx-panels docs 😞 , so, I opened this issue on the sphinx-panels repository: https://github.com/executablebooks/sphinx-panels/issues/73

According to this issue (https://github.com/executablebooks/sphinx-panels/issues/67), it seems like sphinx-panels is getting migrated into sphinx-design (https://github.com/executablebooks/sphinx-design/), but I assumed that they'll migrate the issue there if they want to.
