### ISSUE TITLE
Feedback on Data Hazards

### ISSUE THREAD

**Issue by Lextuga007** [very-good-science/data-hazards#140]
There is no link to a website in the https://github.com/very-good-science/data-hazards/blob/main/CONTRIBUTING.md. 

I'm wanting to copy the approach you take with contributing guidelines in the NHS-R Community 😃 https://github.com/nhs-r-community/demos-and-how-tos/issues/30 and have referenced the https://dataethicsclub.com/contents/join_in/code-of-conduct.html which I really like!

**Comment by ninadicara** [comment]
Fixed @Lextuga007 ! Thank you!
PS The out of office was made with a Github action - if need any tips on setting one up just shout! Ours was inspired by the Turing Way :D

**Comment by Lextuga007** [comment]
That's really interesting! I've been meaning to read the Turing and Apache way as we've just started something similar in our team https://cdu-data-science-team.github.io/the-cdu-way/. Got a bit distracted contributing to that but I love this idea of an out of office!
