### ISSUE TITLE
Data Hazards paper 

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-hazards#150]
This is a growing to-do list of paper preparations
------
- [ ] Plan it: 
    - [ ] General outline 
      - Intro including aims/motivation
      - Introducing the Data Hazard Labels
          - Method of developing (alpha labels)
          - What are the labels? 
      - Evaluating the Data Hazard Labels:  
          - Method of evaluation
          - Results
      - Discussion 
- [ ] Preparations
  - [ ] Harmonise previous data from qualtrics  - @ninadicara 
  - [ ] Recreate images of results - @ninadicara 
  - [ ] Prepare for final workshop to evaluate v1.0 labels.
     - [ ] Adding images to website - @NatalieZelenka 
     - [ ] Adding Leo's app to the website - @NatalieZelenka 
     - [ ] Adding everyone's contributions #131 to the website - @NatalieZelenka 
- [ ] Write it in this [overleaf document](https://www.overleaf.com/project/6048b988c414473f4b2155a1). To get access ask @ninadicara 
  - [ ] How were labels developed: which ones did we start with? Which ones were suggested? See [our proposal](https://datahazards.com/contents/materials/misc/proposal.html)

**Comment by ninadicara** [comment]
Closing as we have moved paper writing to it's own repository for simplicity
