### ISSUE TITLE
Enhancing Research Culture Funding 2022-2023

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-hazards#155]
- A series of events, testing Data Hazards in different contexts/audiences (paid trainers).
  - Academic contexts:  computational neuroscience, digital humanities, psychologies
  - Academic audiences/departments: Bristol Doctoral College, Data Week, Open Research Week: are there any events we can join in with?
  - Geographical areas: Turing and the GW4 potentially. 
  - Public: e.g. We The Curious
  - External partners: anyone have any we could work with together?
- Admin support
- Run the train the trainer
- How things work or don't work in other disciplines?
- Be open about absorbing the good work other people are doing

**Comment by ninadicara** [comment]
Success! We received some funding to run a launch event for Data Hazards 2.0 which is likely to run in May 2023. Here we'll share the new labels, the animations that we have had made an the updated website. We'll share new ways to get involved and introduce new people to the project.
