### ISSUE TITLE
Update Sphinx panels to Sphinx design

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-hazards#158]
Sphinx panels (which we use to display the labels) is no longer supported and has been migrated to Sphinx Design. 
Sphinx Panels requires Sphinx < 5.0 but current version is 6.0 so it is preventing us updating generally too. 

A migration guide for this is available here: https://sphinx-design.readthedocs.io/en/latest/get_started.html#migrating-from-sphinx-panels

Looks like it now uses more typical bootstrap type syntax and grid. 

We should probably do this because I think it will be easier to customise the CSS so that the background colours of the panels are custom, maybe also rich text (#110), and alt-text #14.

**Comment by NatalieZelenka** [comment]
Also: 
- [ ] Check if the requirements file is up to date after this change.

**Comment by ninadicara** [comment]
This issue may also allow us to finally fix the alt-text on the summary page of Hazards #14
