### ISSUE TITLE
Launch event prep

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-hazards#168]
- [x] Extra speakers @NatalieZelenka 
  - [x] Email Phil Clatworthy 
  - [x] Email Kieren, Jazz & Seeralan (Synthetic Biology)
- [x] Last minute advertising
    - [x] LV via Adam @NatalieZelenka  
    - [x] Data Hazards mailing list @ninadicara 
    - [x] Data Ethics Club specific email @ninadicara 
    - [x] Twitter again! @NatalieZelenka @ninadicara 
- [x] Decide plan for the day, to decide how to transport things @NatalieZelenka 
- [x] Reprint the voting sticker sheets A3 (gloss) @NatalieZelenka 
- [x] Print my poster in A2 gloss @NatalieZelenka 
- [x] Banner @ninadicara 
- [ ] Draft slides @ninadicara 
- [x] Ask speakers to send their slides @ninadicara 
- [ ] Claim expenses @NatalieZelenka 
- [x] Order more velcro @NatalieZelenka 
- [x] Better images of AI:
  - [x] Fill in form  @ninadicara (&yasmin)
  - [x] Resizing images. @ninadicara (&yasmin)
  - [x] Write blog post (based on form) @ninadicara  @NatalieZelenka
- [ ] RELEASE!
    - [x] Put the videos up on Youtube @ninadicara 
    - [x] Put them on the website @NatalieZelenka 
    - [ ] #188
    - [x] Update version of website @NatalieZelenka or @ninadicara 
    - [x] Add old suggestions
    - [ ] Fix background colour of panels @NatalieZelenka 
    - [x] Fix favicon @ninadicara 
- [x] Email Data Hazards ambassadors @NatalieZelenka

**Comment by ninadicara** [comment]
See #169 :smile:

**Comment by ninadicara** [comment]
We held the launch event and it was a big success! About 60 people came along and we had a great networking session afterwards. I've converted the release of the ontology file into its own issue as I'm not sure that was ever completed.
