### ISSUE TITLE
Fairness Innovation Challenge

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-hazards#186]
[Competition overview](https://apply-for-innovation-funding.service.gov.uk/competition/1732/overview/c9153422-dbfd-4bc1-99a5-aed7e99dc91a#summary) - Fairness Innovation Challenge - Innovation Funding Service (apply-for-innovation-funding.service.gov.uk)

John shared this with @HDiscoDay - do we want to apply?

- [x] Decide
- [ ] ? Apply

**Comment by NatalieZelenka** [comment]
What do we think @HDiscoDay? @ninadicara? I'm kind of keen.

**Comment by ninadicara** [comment]
We decided not to apply for this in the end because it would stretch us beyond our capacity at the moment - but we thought it looked cool and relevant and we should check it out again next year!
