### ISSUE TITLE
Add Susana as new contributor

### ISSUE THREAD

**Issue by Susana465** [very-good-science/data-hazards#189]
Susana Roman Garcia
* Role: Workshop facilitator, content developer of the Data Hazards application to different settings, especially Neuroscience, PhD case study application of Data Hazards
* ORCID ID: [0009-0004-6967-7754](https://orcid.org/0009-0004-6967-7754)
* Personal website: https://susana465.github.io/website/

I came across the Data Hazards project as I looked for a way to embed thinking about ethics into my PhD, around 2021/22. Since then, I have attended a facilitator training workshop given by Nina and Natalie; and applied the Data Hazards framework to my PhD as I go along. To showcase this, I made a [poster presentation](https://github.com/Susana465/Bias-and-Reproducibility-Poster/blob/main/README.md) for the [COMBINE](https://combine-org.github.io/events/) and [ICSB](https://www.icsb2022.berlin/home) 2022 conferences. 
I have also facilitated a couple of Data Hazard workshops, information for how I prepared can be found here [Data_Hazards_workshops](https://github.com/Susana465/Data_Hazards_workshops). I have also co-organised and co-hosted a [one-day symposium around Data Hazards, Ethics and Reproducibility in 2023](https://github.com/Susana465/der_symposium_20230310). 
Likewise, I also worked with the Data Hazards team to create a [poster](https://github.com/Susana465/DH_Project_CaseStudy) for AI UK 2023, in which I showcased my PhD work for people at the conference to discuss what Data Hazard labels they thought applied. 
I have also worked on adding a chapter to the [Turing Way Booklet](https://the-turing-way.netlify.app/index.html) about Data hazards, which is currently still in the process of being reviewed and published as of January 2024 (see info [here](https://github.com/the-turing-way/the-turing-way/pull/3435)).

**Comment by ninadicara** [comment]
Added!
