### ISSUE TITLE
Set up Open Science Framework project

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-hazards#19]
- [x] Make an [Open Science Framework](osf.io) project

Add:
- [x]  Ethics materials
- [x] Pre-registration
- [x] Link GitHub account (so that all the GitHub files show up in the file browser)
- [x] Add a link to deployed website in wiki/description

**Comment by ninadicara** [comment]
Requested authorisation to link these - will probably go to your email @NatalieThurlby !

**Comment by NatalieThurlby** [comment]
Finally configured the add-on to choose this repo!
