### ISSUE TITLE
Direct harm/physical harm

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-hazards#34]
Just mulling over the definition of the 'May cause direct harm' label. 
It's definition is that it is physical harm - my question is do we want to restrict this to physical harm? 

As an example, I'm thinking about deep fake generators which could cause a lot of psychological harm, or be used for various illegal purposes. 

It might be that that fits better elsewhere but interested in your thoughts! I can see the appeal of having a label restricted just to physical harm - in which case would it be better to change the title of the label to 'may cause physical harm' to be explicit?

**Comment by NatalieThurlby** [comment]
Maybe let's revisit this one after the first workshop!

**Comment by ninadicara** [comment]
We're going to change this on the website. Decided on slightly different wording.

**Comment by NatalieThurlby** [comment]
Nina made a great point that all of the hazards are types of harm.

Direct harm = direct physical or pscyhological harm even if it wasn’t poorly designed or being misused.
