### ISSUE TITLE
Illustrations for the hazards

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-hazards#38]
We'd like to develop some images for the hazards once they are mostly decided upon.

**Comment by ninadicara** [comment]
Here are some ideas of websites that allow you to pay a small free to access professional looking images. (thanks to the people at the Turing for suggesting these sites!)
https://thenounproject.com/
https://streamlinehq.com/

**Comment by ninadicara** [comment]
Had a play around with making a banner image and have uploaded it here - originally intended for the JGI newsletter as an alternative to using the images of the hazards themselves https://github.com/very-good-science/data-hazards/blob/main/images/data-hazards-banner.pdf

**Comment by NatalieThurlby** [comment]
I love it, it looks so cool! I'm still away at the minute, but I'm really excited to look at everything you've done and get organised when I get back on Wednesday :)
