### ISSUE TITLE
Tasks for workshop organising

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-hazards#46]
Tasks for @NatalieThurlby and @ninadicara 

## By 13th August
- [x] Decide tentative dates (we decided 1-3pm on the 21st Sept or 23rd Sept 2022)
- [x] Email Ismael to see if he can make those dates
- [x] Formally set date (Tuesday 21st Sept 1-3pm)
- [x] Email the workshop owners to see if they can make the new date. NB (!) Attach the participant information sheet to this email so that they can read it.
## By 20th August 
- [x] Make Eventbrite with consent sheet built into sign up for attendees - link to participant information sheet. 
- [x] Send the sign up event to all the previously interested parties. 
- [x] Send to Lily to advertise the sign up in the JGI newsletter
## 1 week before workshop
- [x] Send project owners the Qualtrics survey to complete (NB this includes the consent form)
- [x] Ensure Qualtrics is changed and ready to go (See #47)
- [x] Send email to participants
- [x] Send email to Ismael

**Comment by NatalieThurlby** [comment]
I'm going to close this once I've figured out if we can have Joe or if it's going to be Emma
