### ISSUE TITLE
Apply for conferences?

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/data-hazards#58]
It might be nice to take Data Hazards to a conference next year, e.g. 
- FAccT https://facctconference.org/ __march 2022?__
    - Craft session?! Make your own data hazard label 
- Metascience https://metascience2021.org/ __sept 2022?__
- Mozfest: https://www.mozillafestival.org/en/proposals/?utm_source=email&utm_medium=newsletter&utm_campaign=2022_mozfest_newsletter&utm_content=cfp_launch - deadline Nov 2nd
### To-do:
- [x] Have a look and think in November/December?

**Comment by ninadicara** [comment]
Closing now & going to open individual conference issues to make tasks easier to split up :)
