### ISSUE TITLE
Design the asynchronous process for Data Hazards

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-hazards#77]
I've been thinking about how to make filling in Data Hazards asynchronously easy. This is related to #45, but a little more specific.

Using Data Hazards = **LARD**. 

- **L**earn: find out about the data hazard labels: what are they and what's the purpose?
   - [x] Dream: commission a short explainer video
   - [x] Or: Record a basic explainer video
   - [ ] And/Or: update website with this in mind, i.e. minimum you need to know to apply the hazards page
- **A**pply: apply them to your project
   - [ ] Dream: natively do this inside OSF (#76)
   - [ ] Or: Provide a web form that people can fill in where they can download their answers at the end. 
- **R**eflect: reflect on how other people may apply the labels differently, and how you might prevent some of the outcomes that you and others have identified. Getting other people's feedback is optional, but encouraged.
   - [ ] Dream: allow other people to ethics-register your project
   - [ ] Or: provide a mailing list, panel, discussion group, subreddit/whatever, where we apply the labels to registered projects 
- **D**isplay: display your hazard labels in slides, papers, and grant applications:
  -  to let other people know that you've thought about this stuff, and what steps you've taken to minimise negative outcomes
  - to let other people know that when they use the tech/algorithm, they take on the repsonsibility of continuing to ensure that the work is used for everyone's benefit
  - [ ] Add Gareth's app #56, #45 
  - [x] Have a section of the website showing how other people have used the.

## Videos
- [x] Run through hazards - @NatalieThurlby 
- [x] Case study - @ninadicara 

Video aims:
- [ ] keep to 3 mins each
- [ ] speed up-able embedded
- [ ] with transcript

**Comment by NatalieThurlby** [comment]
@ninadicara do you have any feedback on these ramblings?

**Comment by NatalieThurlby** [comment]
Ethics is hard, so we've made you some **LARD**.

(sorry).

**Comment by NatalieThurlby** [comment]
Note: the JGI seedcorn successful participants will be notified on the week commencing the 13th December, which means it would be good to get our asynchronous materials in order by then, so that we can get things rolling with them at that point.

Question: 
- Do we need to alter/update our ethics for this slightly different use case (if we'd like to get feedback from people who use it?)
