### ISSUE TITLE
Create Data Hazards lesson plan materials

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-hazards#79]
- [x] Create lesson page for students (resources they might want during a lecture)
   - [x] Embed the slides
   - [x] List the titles of the Data Hazards
   - [x] Link to the full list of Hazards

- [x] Create lesson plan page for teachers (how to run a teaching session/lecture on it)
  - [x] Timings of lesson we've tried and tested
  - [x] Prep needed on the part of the teacher/lecturer
  - [x] Slides (to reuse or as an example)

**Comment by ninadicara** [comment]
These resources are now on the website and reusable :)
