### ISSUE TITLE
Prepare for creation of animations

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-hazards#89]
- [x] Make a new Data Hazards folder that contains the materials we need for organising the animation video ❤️ 
- [x] Add potential scripts for the case study and the "What is Data Hazards?" video: rule of thumb - no more than 1 page per minute of text (tbf that seems like too much).

**Comment by ninadicara** [comment]
I think we have done these things! 
We will need a new issue I think that better lays out everything we are working towards for the facilitator training in June.
