### ISSUE TITLE
FAccT 2022 

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-hazards#97]
FAccT will be held June 21-24 2022 (Seoul and online). 
We're intending to submit a proposal to FAccT for a CRAFT session. 
Info about these sessions [can be found here](https://facctconference.org/2022/cfcraft.html).

**Deadline: January 28, 2022 at 11:59 PM AoE** (this is 12 noon on Jan 29th in GMT) 

To do:
- [x] Decide which theme we're going to submit against
- [x] Complete the proposal template ([helpfully provided as a Google doc here](https://docs.google.com/document/d/1buuIUSmwt7ljE7_y9z38tBqbGeAA8Rq9/edit?amp;amp;ouid=109708481798365129436&amp;amp;rtpof=true&amp;amp;sd=true))
- [x] Submit the proposal via EasyChair
- [x] Hear outcome of application by 14th March 2022

**Comment by ninadicara** [comment]
RE themes, this is tricky because I think there are elements that align with all of them! If we have to choose one thought I think we'd fit well under 3 - Generating Higher Order Critique.

**Comment by NatalieZelenka** [comment]
No luck this time :(
